name: Create Repository Diagram
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Generate Diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "diagram.svg"
          excluded_paths: "node_modules,dist,build,.vscode,.github"
          should_push: true
          commit_message: "Update repository diagram [skip ci]"
          branch: "main"
