name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'tally-stock-frontend/src/assets/stock-data.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./tally-stock-frontend
        run: npm install

      - name: Build
        working-directory: ./tally-stock-frontend
        run: npm run build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: tally-stock-frontend/dist
